# LMNA Lipodystrophy, familial partial, type 2 

Data taken from [Xiao C, et al. (2023) The Clinical Characteristics and Potential Molecular Mechanism of LMNA Mutation-Related Lipodystrophy. Adv Biol (Weinh). 2023 Sep;7(9):e2200301. PMID:37303127](https://pubmed.ncbi.nlm.nih.gov/37303127/)

The study included six individuals (with a male to female ratio of 1:2), with a mean age of onset of 18 ± 21.62 years and a mean age of diagnosis of 30.33 ± 22.87 years. All patients were presented with glucose intolerance or diabetes and insulin resistance. Five out of the six patients had hyperlipidemia, and two out of the six had fatty liver disease. Creatinine levels of all participants were within the normal range, with a mean value of 48.3 ± 21.7 μmol L−1 . However, we observed elevated levels of albuminuria in three out of six patients with T10I or R482W mutations, as indicated by a higher urine albumin-to-creatinine ratio (UACR),
suggesting potential kidney injury in these patients. 

All six patients showed elevated postprandial in-
sulin levels, with cases 3 and 4 having insulin levels greater than
300 uIU mL−1 , indicating insulin resistance in all six patients.
This was confirmed by homeostatic model assessment of insulin
resistance (HOMA-IR) values. In terms of gonad involvement,
one patient (case 2 with L59V mutation) was diagnosed with pre-
mature ovarian failure without determined reasons, while an-
other patient (case 4 with heterozygous R482W mutation) was di-
agnosed with polycystic ovary syndrome (PCOS).

In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', None) # show entire column contents, important!
from IPython.display import display, HTML
from pyphetools.creation import *
from pyphetools.visualization import *
from pyphetools.validation import *
import pyphetools
print(f"Using pyphetools version {pyphetools.__version__}")

Using pyphetools version 0.9.65

In [2]:
PMID = "PMID:37303127"
title = "The Clinical Characteristics and Potential Molecular Mechanism of LMNA Mutation-Related Lipodystrophy"
cite = Citation(pmid=PMID, title=title)
parser = HpoParser(hpo_json_file="../hp.json")
hpo_cr = parser.get_hpo_concept_recognizer()
hpo_version = parser.get_version()
hpo_ontology = parser.get_ontology()
metadata = MetaData(created_by="ORCID:0000-0002-0736-9199", citation=cite)
metadata.default_versions_with_hpo(version=hpo_version)
print(f"HPO version {hpo_version}")

HPO version 2024-02-27

In [3]:
df = pd.read_excel("input/Xiao2023_LMNA.xlsx")
df.head(2)

,Case,Gender,Age onset,Age diagnosis,Family history,BMI [kg m−2],Nucleotide mutation,Amino acid mutation,Zygosity,Lipodystrophy phenotype,...,LAAPD,RVAPD,IVS,LVPW,LVIDd,LVIDs,FS%,EF%,ECG,Cardiac MRI
0,1,M,7,16,none,14.1,c.29C>T,p.T10I,Het,Generalized,...,25,17,8,7,41,25,49,71,Normal,ND
1,2,F,6,21,Father hypertension,13.1,c.175C>G,p.L59V,Het,Generalized,...,29,35,8,8,44,36,19,39,"Junctional escape rhythm, QT interval prolongation","Enlarged right heart, tricuspid valve insufficiency, myocardial lesions, aortic valve, mitral valve reflux"

In [4]:
#res = OptionColumnMapper.autoformat(df=df, concept_recognizer=hpo_cr)

In [5]:
column_mapper_list = list()

In [6]:
lipodystrophy_d = {'Generalized': 'Generalized lipodystrophy',
 'Partial': 'Lipodystrophy'}
# TODO work out terms for partial dystrophy
lipodystrophyMapper = OptionColumnMapper(column_name='Lipodystrophy phenotype',
                                                   concept_recognizer=hpo_cr, option_d=lipodystrophy_d)
column_mapper_list.append(lipodystrophyMapper)
lipodystrophyMapper.preview_column(df)

                                             mapping count
0  Generalized lipodystrophy (HP:0009064) (observed)     3
1              Lipodystrophy (HP:0009125) (observed)     3

In [7]:
endocrine_d = {'Diabetes': 'Diabetes mellitus',
 'insulin resistance': 'Insulin resistance',
 'nonalcoholic fatty liver': 'Hepatic steatosis',
 'osteoporosis': 'Osteoporosis',
 'hyperlipidemia': 'Hyperlipidemia',
 'Glucose intolerance': 'Glucose intolerance',
 'short stature': 'Short stature',
}
endocrineMapper = OptionColumnMapper(column_name='Endocrinopathies', concept_recognizer=hpo_cr, option_d=endocrine_d)
column_mapper_list.append(endocrineMapper)
endocrineMapper.preview_column(df)

                                       mapping count
0    Diabetes mellitus (HP:0000819) (observed)     4
1   Insulin resistance (HP:0000855) (observed)     6
2    Hepatic steatosis (HP:0001397) (observed)     4
3         Osteoporosis (HP:0000939) (observed)     2
4       Hyperlipidemia (HP:0003077) (observed)     5
5  Glucose intolerance (HP:0001952) (observed)     2
6        Short stature (HP:0004322) (observed)     1

In [8]:
nonendocrine_d = {'Progeroid appearance': 'Progeroid facial appearance',
 'skin pigmentation': 'Hyperpigmentation of the skin',
 #'bilateral femoral fractures': 'PLACEHOLDER',
 'liver insufficiency': 'Decreased liver function',
 'cardiomyopathy': 'Cardiomyopathy',
 'heart failure': 'Congestive heart failure',
 'junctional escape rhythm': 'Ventricular escape rhythm',
 'premature ovarian failure': 'Premature ovarian insufficiency',
 'café au lait spots': 'Cafe-au-lait spot',
 'scoliosis': 'Scoliosis',
 'QT intervals prolongation': 'Prolonged QT interval',
 'ST-T changes': 'Abnormal ST segment',
 'Dilated cardiomyopathy': 'Dilated cardiomyopathy',
 'persistent atrial fibrillation': 'Atrial fibrillation',
 'abnormal liver function': 'Elevated hepatic transaminase',
 'achilles tendon contracture': 'Achilles tendon contracture',
 'muscular dystrophy': 'Muscular dystrophy',
 'myotonia': 'Myotonia'}
nonendocrineMapper = OptionColumnMapper(column_name='Nonendocrine disease',concept_recognizer=hpo_cr, option_d=nonendocrine_d)
column_mapper_list.append(nonendocrineMapper)
nonendocrineMapper.preview_column(df)

                                                    mapping count
0       Progeroid facial appearance (HP:0005328) (observed)     2
1     Hyperpigmentation of the skin (HP:0000953) (observed)     1
2          Decreased liver function (HP:0001410) (observed)     1
3                    Cardiomyopathy (HP:0001638) (observed)     1
4          Congestive heart failure (HP:0001635) (observed)     2
5         Ventricular escape rhythm (HP:0005155) (observed)     1
6   Premature ovarian insufficiency (HP:0008209) (observed)     1
7                 Cafe-au-lait spot (HP:0000957) (observed)     1
8                         Scoliosis (HP:0002650) (observed)     2
9             Prolonged QT interval (HP:0001657) (observed)     1
10              Abnormal ST segment (HP:0012249) (observed)     1
11           Dilated cardiomyopathy (HP:0001644) (observed)     1
12              Atrial fibrillation (HP:0005110) (observed)     1
13    Elevated hepatic transaminase (HP:0002910) (observed)     1
14      Achilles tendon contracture (HP:0001771) (observed)     1
15               Muscular dystrophy (HP:0003560) (observed)     1
16                         Myotonia (HP:0002486) (observed)     1

In [9]:
# The normal range veries in different labs. The authors called the following values abnormal
alt_d = {'62': 'Elevated circulating alanine aminotransferase concentration',
  '138': 'Elevated circulating alanine aminotransferase concentration',
 '59': 'Elevated circulating alanine aminotransferase concentration'}
alt = Thresholder.ALT_blood()
altMapper = ThresholdedColumnMapper(column_name='ALT', thresholder=alt)
column_mapper_list.append(altMapper)
altMapper.preview_column(df)

,mapping: 7.0-56.0 U/L,count
0,Elevated circulating alanine aminotransferase concentration (HP:0031964): observed,3
1,Elevated circulating alanine aminotransferase concentration (HP:0031964): excluded,3

In [10]:
#The normal range is 8 to 33 U/L
ast_d = {'49': 'Elevated circulating aspartate aminotransferase concentration',
 '151': 'Elevated circulating aspartate aminotransferase concentration',
 '36': 'Elevated circulating aspartate aminotransferase concentration'}
ast = Thresholder.AST_blood(unit="U/L", low_thresh=8, high_thresh=33)
astMapper = ThresholdedColumnMapper(column_name='AST', thresholder=ast)
column_mapper_list.append(astMapper)
astMapper.preview_column(df)

,mapping: 8.0-33.0 U/L,count
0,Elevated circulating aspartate aminotransferase concentration (HP:0031956): observed,3
1,Elevated circulating aspartate aminotransferase concentration (HP:0031956): excluded,3

In [11]:
# All crea values were noted to be normal
crMapper = ConstantColumnMapper(column_name="Cr",hpo_id="HP:0012100", hpo_label="Abnormal circulating creatinine concentration", excluded=True)
column_mapper_list.append(crMapper)
#crMapper.preview_column(df)

In [12]:
# normal 208 – 428 µmol/L (male)
ua = Thresholder.uric_acid_blood(unit="umol/L", low_thresh=208, high_thresh=428)
uaMapper = ThresholdedColumnMapper(column_name="UA", thresholder=ua)
column_mapper_list.append(uaMapper)
uaMapper.preview_column(df)

            mapping: 208.0-428.0 umol/L count
0  Hyperuricemia (HP:0002149): excluded     3
1  Hyperuricemia (HP:0002149): observed     3

In [13]:
# UACR  PMID: 34089300
# The normal UACR value is less than or equal to 17 mg/g in men but in women, the level is observed to be higher ranging around 25 mg/g.
# Implies albuminuria
albumin = Thresholder.albumin_urine(unit="mg/g", high_thresh=17)
uacrMapper = ThresholdedColumnMapper(column_name='UACR', thresholder= albumin)
column_mapper_list.append(uacrMapper)
uacrMapper.preview_column(df)

                  mapping: None-17.0 mg/g count
0      Albuminuria (HP:0012592): observed     3
1  Albuminuria (HP:0012592): not measured     3

In [14]:
# Normal range, below 3.4 mmol/L
ldl = Thresholder.LDL_cholesterol_blood(unit="mmol/L", high_thresh=3.4, low_thresh=0.4)
ldlMapper = ThresholdedColumnMapper(column_name='LDLc', thresholder=ldl)
column_mapper_list.append(ldlMapper)
ldlMapper.preview_column(df)

                                          mapping: 0.4-3.4 mmol/L count
0   Abnormal LDL cholesterol concentration (HP:0031886): excluded     5
1  Increased LDL cholesterol concentration (HP:0003141): observed     1

In [15]:
# Desirable range: Levels above 40 mg/dL (1 mmol/L) in men and above 50 mg/dL (1.3 mmol/L) in women
# Decreased HDL cholesterol concentration HP:0003233
hdlc_d = {'0.65': 'PLACEHOLDER',
 '0.84': 'PLACEHOLDER',
 '0.64': 'PLACEHOLDER',
 '1.32': 'PLACEHOLDER',
 '1.52': 'PLACEHOLDER',
 '0.75': 'PLACEHOLDER'}
hdl = Thresholder.HDL_cholesterol_blood(unit="mmol/L", low_thresh=1.0, high_thresh=2.3)
hdlcMapper = ThresholdedColumnMapper(column_name='HDLc', thresholder=hdl)
column_mapper_list.append(hdlcMapper)
hdlcMapper.preview_column(df)

                                          mapping: 1.0-2.3 mmol/L count
0  Decreased HDL cholesterol concentration (HP:0003233): observed     4
1   Abnormal HDL cholesterol concentration (HP:0031888): excluded     2

In [16]:
# Less than 150 mg/dL (1.69 mmol/L) Borderline high: 150 to 199 mg/dL (1.69 to 2.25 mmol/L) 
# High: 200 to 499 mg/dL (2.26 to 5.64 mmol/L) Very high: 500 mg/dL or above 
# Hypertriglyceridemia HP:0002155
tg_d = {'3.85': 'PLACEHOLDER',
 '1.11': 'PLACEHOLDER',
 '39.91': 'PLACEHOLDER',
 '0.69': 'PLACEHOLDER',
 '3.31': 'PLACEHOLDER',
 '3.59a)': 'PLACEHOLDER'}
tg = Thresholder.triglyceride_blood(unit="mmol/L", high_thresh=1.69)
tgMapper =  ThresholdedColumnMapper(column_name='TG', thresholder=tg)
column_mapper_list.append(tgMapper)
tgMapper.preview_column(df)

                         mapping: None-1.69 mmol/L count
0      Hypertriglyceridemia (HP:0002155): observed     4
1  Hypertriglyceridemia (HP:0002155): not measured     2

In [17]:
# Total cholesterol: Levels below 200 mg/dL (5.2 mmol/L)
tc = Thresholder.total_cholesterol_blood(unit="mmol/L", high_thresh=5.2)
tcMapper =  ThresholdedColumnMapper(column_name='TC', thresholder=tc)
column_mapper_list.append(tcMapper)
tcMapper.preview_column(df)

                          mapping: None-5.2 mmol/L count
0  Hypercholesterolemia (HP:0003124): not measured     4
1      Hypercholesterolemia (HP:0003124): observed     2

In [18]:
# The normal fasting serum FFAs level is 0.1 to 0.45 mmol/L for females and 0.1 to 0.6 mmol/L for males
# note the table has umol not mmol, so the threshold is 450
# Increased circulating free fatty acid level HP:0030781
ffa_d = {'455': 'PLACEHOLDER',
 '250': 'PLACEHOLDER',
 '1569': 'PLACEHOLDER',
 '361': 'PLACEHOLDER',
 '703': 'PLACEHOLDER',
 '359': 'PLACEHOLDER'}
ffa = Thresholder.free_fatty_acid_blood(unit="umol/L", low_thresh=100, high_thresh=600)
ffaMapper = ThresholdedColumnMapper(column_name='FFA', thresholder=ffa)
column_mapper_list.append(ffaMapper)
ffaMapper.preview_column(df)

,mapping: 100.0-600.0 umol/L,count
0,Abnormal circulating free fatty acid concentration (HP:0040300): excluded,4
1,Increased circulating free fatty acid level (HP:0030781): observed,2

In [19]:
#0.3 to 1.0 mg/dL
# Elevated circulating C-reactive protein concentration HP:0011227
hscrp_d = {'4.72': 'PLACEHOLDER',
 '2.83': 'PLACEHOLDER',
 '3.99': 'PLACEHOLDER',
 '2.9': 'PLACEHOLDER',
 '0.41': 'PLACEHOLDER',
 '0.26': 'PLACEHOLDER'}
crp_term = HpTerm(hpo_id="HP:0011227", label="Elevated circulating C-reactive protein concentration")
crp = Thresholder(unit="mg/dL", hpo_term_high=crp_term, threshold_high=1.0)
hscrpMapper =  ThresholdedColumnMapper(column_name='hsCRP', thresholder=crp)
column_mapper_list.append(hscrpMapper)
hscrpMapper.preview_column(df)

,mapping: None-1.0 mg/dL,count
0,Elevated circulating C-reactive protein concentration (HP:0011227): observed,4
1,Elevated circulating C-reactive protein concentration (HP:0011227): not measured,2

In [20]:
# FBG, fasting blood glucose; 70 mg/dL (3.9 mmol/L) and 100 mg/dL (5.6 mmol/L). 
# Hyperglycemia HP:0003074
fbg_d = {'6.6': 'PLACEHOLDER',
 '4.6': 'PLACEHOLDER',
 '18.8': 'PLACEHOLDER',
 '6.0': 'PLACEHOLDER',
 '8.8': 'PLACEHOLDER'}
glucose = Thresholder.glucose_blood(unit="mmol/L", low_thresh=3.9, high_thresh=5.6)
fbgMapper = ThresholdedColumnMapper(column_name='FBG', thresholder=glucose)
column_mapper_list.append(fbgMapper)
fbgMapper.preview_column(df)

                                       mapping: 3.9-5.6 mmol/L count
0                         Hyperglycemia (HP:0003074): observed     5
1  Abnormal blood glucose concentration (HP:0011015): excluded     1

In [21]:
## below 5.7 %. 5.7 % to 6.4 %  prediabetic, while diabetes can be diagnosed with a HbA1c of 6.5% or high
## Elevated hemoglobin A1c HP:0040217
hba1c_d = {'6.5': 'PLACEHOLDER',
 '6.7': 'PLACEHOLDER',
 '11.9': 'PLACEHOLDER',
 '5.7': 'PLACEHOLDER',
 '6.9': 'PLACEHOLDER',
 '9.6': 'PLACEHOLDER'}
hba1c_term = HpTerm(label="Elevated hemoglobin A1c", hpo_id="HP:0040217")
hba1c = Thresholder(hpo_term_high=hba1c_term, hpo_term_abn=hba1c_term, unit="%", threshold_high=6.5)
hba1cMapper = ThresholdedColumnMapper(column_name='HbA1c', thresholder=hba1c)
column_mapper_list.append(hba1cMapper)
hba1cMapper.preview_column(df)

                                  mapping: None-6.5 % count
0  Elevated hemoglobin A1c (HP:0040217): not measured     2
1      Elevated hemoglobin A1c (HP:0040217): observed     4

In [22]:
#FI, fasting insulin; 
# Hyperinsulinemia HP:0000842
#5 and 15 µU/mL but
fi_d = {'77.19': 'PLACEHOLDER',
 '12.79': 'PLACEHOLDER',
 '167.48': 'PLACEHOLDER',
 '29.2': 'PLACEHOLDER',
 '18.31': 'PLACEHOLDER',
 '13.1': 'PLACEHOLDER'}
insulin = Thresholder.insulin_blood(unit="uU/mL", low_thresh=5, high_thresh=15)
fiMapper = ThresholdedColumnMapper(column_name='FI', thresholder=insulin)
column_mapper_list.append(fiMapper)
fiMapper.preview_column(df)

                   mapping: 5.0-15.0 uU/mL count
0  Hyperinsulinemia (HP:0000842): observed     4
1  Hyperinsulinemia (HP:0000842): excluded     2

In [23]:
# CK females is 30 to 145 U/L; males 55 to 170 U/L
# Elevated circulating creatine kinase concentration HP:0003236

ck_d = {'ND': 'PLACEHOLDER',
 '65': 'PLACEHOLDER',
 '50': 'PLACEHOLDER',
 '45': 'PLACEHOLDER',
 '39': 'PLACEHOLDER',
 '481': 'PLACEHOLDER'}
ck = Thresholder.creatine_kinase_blood(unit="U/L", low_thresh=30, high_thresh=170)
ckMapper = ThresholdedColumnMapper(column_name='CK', thresholder=ck)
column_mapper_list.append(ckMapper)
ckMapper.preview_column(df)

,mapping: 30.0-170.0 U/L,count
0,Abnormal circulating creatine kinase concentration (HP:0040081): not measured,1
1,Abnormal circulating creatine kinase concentration (HP:0040081): excluded,4
2,Elevated circulating creatine kinase concentration (HP:0003236): observed,1

In [24]:
# NT-proBNP < 100 picograms per milliliter (pg/mL)
# Increased circulating NT-proBNP concentration HP:0031185

ntprobnp_d = {'ND': 'PLACEHOLDER',
 '1673': 'PLACEHOLDER',
 '72': 'PLACEHOLDER',
 '60': 'PLACEHOLDER',
 '138': 'PLACEHOLDER',
 '746': 'PLACEHOLDER'}
ntprobnp = Thresholder.NTproBNP_blood(unit="pg/mL", high_thresh=100,low_thresh=0)
ntprobnpMapper = ThresholdedColumnMapper(column_name='NT-proBNP', thresholder=ntprobnp)
column_mapper_list.append(ntprobnpMapper)
ntprobnpMapper.preview_column(df)

,mapping: 0.0-100.0 pg/mL,count
0,Increased circulating NT-proBNP concentration (HP:0031185): not measured,1
1,Increased circulating NT-proBNP concentration (HP:0031185): observed,3
2,Increased circulating NT-proBNP concentration (HP:0031185): excluded,2

In [25]:
# Normall 50-70%
ef_d = {
 '39': 'Moderately reduced left ventricular ejection fraction',
 '40': 'Mildly reduced left ventricular ejection fraction'}
excluded = {'71': 'Reduced left ventricular ejection fraction',
           '69': 'Reduced left ventricular ejection fraction',
 '74': 'Reduced left ventricular ejection fraction',
 '73': 'Reduced left ventricular ejection fraction',}
efMapper = OptionColumnMapper(column_name='EF%', concept_recognizer=hpo_cr, option_d=ef_d, excluded_d=excluded)
column_mapper_list.append(efMapper)
efMapper.preview_column(df)

,mapping,count
0,Reduced left ventricular ejection fraction (HP:0012664) (excluded),4
1,Moderately reduced left ventricular ejection fraction (HP:0012665) (observed),1
2,Mildly reduced left ventricular ejection fraction (HP:0012663) (observed),1

In [26]:
ecg_d = {
 'Junctional escape rhythm': 'Ventricular escape rhythm',
 'QT interval prolongation': 'Prolonged QT interval',
 'ST-T changes': 'Abnormal ST segment',
 'Continuous atrial fibrillation': 'Atrial fibrillation'}
ecgMapper = OptionColumnMapper(column_name='ECG',concept_recognizer=hpo_cr, option_d=ecg_d)
column_mapper_list.append(ecgMapper)
ecgMapper.preview_column(df)

                                             mapping count
0  Ventricular escape rhythm (HP:0005155) (observed)     1
1      Prolonged QT interval (HP:0001657) (observed)     2
2        Abnormal ST segment (HP:0012249) (observed)     1
3        Atrial fibrillation (HP:0005110) (observed)     1

In [27]:
cardiac_mri_d = {
 'tricuspid valve insufficiency': 'Tricuspid regurgitation',
 'mitral valve reflux': 'Mitral regurgitation',
 'Enlargement of the right atrium': 'Right atrial enlargement',
 'pulmonary hypertension': 'Pulmonary arterial hypertension'}
cardiac_mriMapper = OptionColumnMapper(column_name='Cardiac MRI',concept_recognizer=hpo_cr, option_d=cardiac_mri_d)
column_mapper_list.append(cardiac_mriMapper)
cardiac_mriMapper.preview_column(df)

                                                   mapping count
0          Tricuspid regurgitation (HP:0005180) (observed)     1
1             Mitral regurgitation (HP:0001653) (observed)     1
2         Right atrial enlargement (HP:0030718) (observed)     1
3  Pulmonary arterial hypertension (HP:0002092) (observed)     1

In [28]:
onsetMapper = AgeColumnMapper.by_year('Age onset')
#ageMapper.preview_column(df['Age onset'])
encounterMapper = AgeColumnMapper.by_year('Age diagnosis') 
sexMapper = SexColumnMapper(male_symbol="M", female_symbol="F", column_name="Gender")
#sexMapper.preview_column(df['Gender'])

In [29]:
LMNA_transcript = "NM_170707.4"
vman = VariantManager(df=df, individual_column_name="Case", allele_1_column_name='Nucleotide mutation', gene_symbol="LMNA",
                      transcript=LMNA_transcript)
var_d = vman.get_variant_d()
print(f"Extracted {len(var_d)} variants with Variant Validator")
varMapper = VariantColumnMapper(variant_d=var_d,
                                variant_column_name='Nucleotide mutation',
                                default_genotype="heterozygous")

Extracted 38 variants with Variant Validator

In [30]:
encoder = CohortEncoder(df=df, 
                        hpo_cr=hpo_cr, 
                        column_mapper_list=column_mapper_list, 
                        individual_column_name="Case", 
                        age_at_last_encounter_mapper=encounterMapper,
                        age_of_onset_mapper=onsetMapper,
                        variant_mapper=varMapper,
                        sexmapper=sexMapper,
                        metadata=metadata)
omim_id = "OMIM:151660"
omim_label = "Lipodystrophy, familial partial, type 2"
lipodystrophy = Disease(disease_id=omim_id, disease_label=omim_label)
encoder.set_disease(disease=lipodystrophy)
individuals = encoder.get_individuals()

In [31]:
cvalidator = CohortValidator(cohort=individuals, ontology=hpo_ontology, min_hpo=1, allelic_requirement=AllelicRequirement.MONO_ALLELIC)
qc = QcVisualizer(cohort_validator=cvalidator)
display(HTML(qc.to_summary_html()))

In [32]:
individuals = cvalidator.get_error_free_individual_list()
phenopackets = [i.to_ga4gh_phenopacket(metadata=metadata.to_ga4gh()) for i in individuals]
table = PhenopacketTable(phenopacket_list=phenopackets)
display(HTML(table.to_html()))

In [33]:
Individual.output_individuals_as_phenopackets(individual_list=individuals,
                                              metadata=metadata)

We output 6 GA4GH phenopackets to the directory phenopackets